# Generated by Django 5.2.5 on 2025-08-07 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("City", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("propertyName", models.CharField(max_length=50)),
                ("propertyPoster", models.CharField(max_length=500)),
                ("propertyDescription", models.CharField(max_length=500)),
                ("propertyPrice", models.IntegerField(default=0)),
                ("propertySize", models.IntegerField(default=500)),
                (
                    "propertyCity",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="City.citymodel",
                    ),
                ),
            ],
        ),
    ]
